version: "3.8"

services:
  mysql-db: 
    image: mysql:5.7
    container_name: "mysql-cont"
    environment:
      MYSQL_ROOT_PASSWORD: "admin@123"
      MYSQL_DATABASE: "devops"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - pythonflask-nw
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "python-flask-mysql-app:v07aug25"
    container_name: "flask-cont"
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: "mysql-cont"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin@123"
      MYSQL_DB: "devops"
    depends_on:
      - mysql-db
    networks:
      - pythonflask-nw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: "nginx-cont"
    ports:
      - "80:80"
    networks:
      - pythonflask-nw
    depends_on:
      - flask-app
    restart: always


networks:
  pythonflask-nw:
    driver: bridge

volumes:
  mysql-data:
    driver: local
